# Generated by Django 2.2.4 on 2019-09-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='picklerick.gif', upload_to=''),
        ),
    ]
